<a href="https://colab.research.google.com/github/solar71830/CASVD/blob/main/casvdd_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from prince import CA,datasets
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

In [ ]:
df = pd.read_csv("heart_failure_clinical_records_dataset.csv")
df

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

In [ ]:
chi2,p,dof,expected=chi2_contingency(df,correction=False)
print(chi2,p)

564685.3012789318 0.0


In [ ]:
N=np.sum(df)
min_dim=min(df.shape)-1
print(np.sqrt((chi2/N)/min_dim))

age                          1.608438
anaemia                     19.099314
creatinine_phosphokinase     0.520086
diabetes                    19.402496
ejection_fraction            2.032862
high_blood_pressure         21.169859
platelets                    0.024446
serum_creatinine            10.625867
serum_sodium                 1.073276
sex                         15.574415
smoking                     22.139969
time                         1.099183
DEATH_EVENT                 22.139969
dtype: float64


C:\Users\Piotrek\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)


In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
n=float(df.sum().sum())
corrMatrix=np.matrix(df.copy(),dtype=float)
for i in range(len(corrMatrix)):
    for j in range(len(corrMatrix[0])):
        corrMatrix[i][j]=corrMatrix[i][j]/n
print(corrMatrix)
dimx=corrMatrix.shape[0]
dimy=corrMatrix.shape[1]

[[9.49024024e-07 0.00000000e+00 7.36442643e-06 ... 0.00000000e+00
  5.06146146e-08 1.26536537e-08]
 [6.95950951e-07 0.00000000e+00 9.94703714e-05 ... 0.00000000e+00
  7.59219219e-08 1.26536537e-08]
 [8.22487488e-07 0.00000000e+00 1.84743343e-06 ... 1.26536537e-08
  8.85755756e-08 1.26536537e-08]
 ...
 [5.69414415e-07 0.00000000e+00 2.60665265e-05 ... 0.00000000e+00
  3.51771572e-06 0.00000000e+00]
 [5.69414415e-07 0.00000000e+00 3.05332663e-05 ... 1.26536537e-08
  3.54302302e-06 0.00000000e+00]
 [6.32682683e-07 0.00000000e+00 2.48011612e-06 ... 1.26536537e-08
  3.60629129e-06 0.00000000e+00]]


In [ ]:
colMass=corrMatrix.sum(axis=0)
colMass=np.transpose(colMass)
colMass

matrix([[2.30161533e-04],
        [1.63232132e-06],
        [2.20135613e-03],
        [1.58170671e-06],
        [1.44087154e-04],
        [1.32863363e-06],
        [9.96399946e-01],
        [5.27366323e-06],
        [5.16914405e-04],
        [2.45480881e-06],
        [1.21475075e-06],
        [4.92834503e-04],
        [1.21475075e-06]])

In [ ]:
rowMass=np.squeeze(corrMatrix.sum(axis=1),axis=1)
rowMass=np.transpose(rowMass)
rowMass

matrix([[0.00336354],
        [0.00343492],
        [0.00205459],
        [0.00266144],
        [0.00414249],
        [0.00258545],
        [0.00161318],
        [0.00575212],
        [0.00333798],
        [0.00491462],
        [0.0046609 ],
        [0.00320736],
        [0.00173618],
        [0.00349759],
        [0.00540706],
        [0.00060313],
        [0.00332072],
        [0.00211044],
        [0.00300371],
        [0.00111132],
        [0.00349618],
        [0.003763  ],
        [0.00366309],
        [0.00466079],
        [0.00334318],
        [0.00189095],
        [0.00248534],
        [0.00359877],
        [0.00194012],
        [0.0025351 ],
        [0.00334359],
        [0.00455934],
        [0.00404278],
        [0.00382658],
        [0.00238373],
        [0.00289587],
        [0.00286439],
        [0.00407659],
        [0.00389628],
        [0.00416951],
        [0.00334311],
        [0.00194078],
        [0.00235186],
        [0.00276381],
        [0.00246603],
        [0

In [ ]:
diagRow=np.eye(len(corrMatrix))
for i in range(len(diagRow)):
    for j in range(len(diagRow[0])):
        diagRow[i][j]=diagRow[i][j]*rowMass[i]
print(diagRow)

C:\Users\Piotrek\AppData\Local\Temp\ipykernel_11720\307641237.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  diagRow[i][j]=diagRow[i][j]*rowMass[i]


[[0.00336354 0.         0.         ... 0.         0.         0.        ]
 [0.         0.00343492 0.         ... 0.         0.         0.        ]
 [0.         0.         0.00205459 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.00942169 0.         0.        ]
 [0.         0.         0.         ... 0.         0.00180845 0.        ]
 [0.         0.         0.         ... 0.         0.         0.00500725]]


In [ ]:
diagCol=np.eye(dimy)
for i in range(len(diagCol)):
    for j in range(len(diagCol[0])):
        diagCol[i][j]=diagCol[i][j]*colMass[i]
print(diagCol)

[[2.30161533e-04 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 1.63232132e-06 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.20135613e-03 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.58170671e-06
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.44087154e-04 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+0

C:\Users\Piotrek\AppData\Local\Temp\ipykernel_11720\444373179.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  diagCol[i][j]=diagCol[i][j]*colMass[i]


In [ ]:
dR=np.linalg.inv(diagRow)
rowProfile=np.dot(dR,corrMatrix)
rowProfile

matrix([[2.82150165e-04, 0.00000000e+00, 2.18948528e-03, ...,
         0.00000000e+00, 1.50480088e-05, 3.76200220e-06],
        [2.02610261e-04, 0.00000000e+00, 2.89585321e-02, ...,
         0.00000000e+00, 2.21029376e-05, 3.68382293e-06],
        [4.00317051e-04, 0.00000000e+00, 8.99173684e-04, ...,
         6.15872386e-06, 4.31110670e-05, 6.15872386e-06],
        ...,
        [6.04365290e-05, 0.00000000e+00, 2.76665000e-03, ...,
         0.00000000e+00, 3.73363446e-04, 0.00000000e+00],
        [3.14862783e-04, 0.00000000e+00, 1.68836421e-02, ...,
         6.99695073e-06, 1.95914620e-03, 0.00000000e+00],
        [1.26353371e-04, 0.00000000e+00, 4.95305214e-04, ...,
         2.52706742e-06, 7.20214214e-04, 0.00000000e+00]])

In [ ]:
dC=np.linalg.inv(diagCol)
colProfile=np.dot(corrMatrix,dC)
colProfile

matrix([[0.0041233 , 0.        , 0.0033454 , ..., 0.        , 0.0001027 ,
         0.01041667],
        [0.00302375, 0.        , 0.04518595, ..., 0.        , 0.00015405,
         0.01041667],
        [0.00357352, 0.        , 0.00083923, ..., 0.01041667, 0.00017973,
         0.01041667],
        ...,
        [0.00247398, 0.        , 0.01184112, ..., 0.        , 0.00713772,
         0.        ],
        [0.00247398, 0.        , 0.01387021, ..., 0.01041667, 0.00718907,
         0.        ],
        [0.00274886, 0.        , 0.00112663, ..., 0.01041667, 0.00731745,
         0.        ]])

In [ ]:
ca=CA(n_components=12)
ca=ca.fit(df)
ca.eigenvalues_summary

eigenvalue % of variance % of variance (cumulative)
component                                                    
0              0.007        92.51%                     92.51%
1              0.000         5.63%                     98.14%
2              0.000         1.34%                     99.48%
3              0.000         0.20%                     99.68%
4              0.000         0.08%                     99.76%
5              0.000         0.05%                     99.81%
6              0.000         0.05%                     99.86%
7              0.000         0.04%                     99.90%
8              0.000         0.03%                     99.94%
9              0.000         0.03%                     99.96%
10             0.000         0.02%                     99.99%
11             0.000         0.01%                    100.00%

In [ ]:
ca.row_coordinates(df).head()

0         1         2         3         4         5         6   \
0 -0.001091 -0.019532  0.009685 -0.006172 -0.001576  0.000561 -0.000107   
1  0.569323 -0.047467  0.000103  0.001141 -0.000278  0.000481 -0.000229   
2 -0.027900 -0.009318  0.023170 -0.008892  0.001314 -0.003625  0.003017   
3 -0.036272 -0.014748  0.013359 -0.005346  0.005481  0.001209  0.000656   
4 -0.037623 -0.021104  0.003200 -0.003881 -0.000868  0.002700 -0.000372   

         7         8         9         10        11  
0  0.001844  0.001231  0.001423 -0.000400 -0.000879  
1 -0.000062 -0.000701  0.001189  0.000301 -0.000732  
2 -0.001442  0.000219  0.001764  0.001069  0.000750  
3 -0.000175 -0.002768  0.000986 -0.000173 -0.001163  
4 -0.001746 -0.000510 -0.000953 -0.000166  0.000640

In [ ]:
ca.column_coordinates(df).head()

0         1         2         3         4   \
age                       0.094278  0.323755  0.337821 -0.086930 -0.113757   
anaemia                  -0.060902  0.201319  0.496662  0.044790  0.179201   
creatinine_phosphokinase  1.728418 -0.021724 -0.003307  0.000099 -0.000190   
diabetes                  0.060955  0.346764  0.164889  0.004479  0.216417   
ejection_fraction         0.093534  0.329650  0.290016  0.279202 -0.026498   

                                5         6         7         8         9   \
age                      -0.004402 -0.016980 -0.003119 -0.000896 -0.002990   
anaemia                   0.290431 -0.297401  0.161284 -0.817989 -0.732969   
creatinine_phosphokinase  0.000057 -0.000050  0.000047 -0.000023 -0.000085   
diabetes                  0.261246 -0.495014 -0.721614  0.671907 -0.554399   
ejection_fraction         0.000933  0.011219 -0.005262  0.002741  0.001719   

                                10        11  
age                      -0.003711  0.003246  
anaemia                   0.122595 -0.030653  
creatinine_phosphokinase -0.000010  0.000018  
diabetes                 -0.056462 -0.056295  
ejection_fraction         0.010925 -0.005066

In [ ]:
ca.scree_plot()

alt.Chart(...)

In [ ]:
ca.plot(df,x_component=0,
    y_component=1,
    show_row_markers=True,
    show_column_markers=True,
    show_row_labels=False,
    show_column_labels=False)

alt.LayerChart(...)

In [ ]:
ca.plot(df,x_component=0,
    y_component=1,
    show_row_markers=False,
    show_column_markers=False,
    show_row_labels=False,
    show_column_labels=True)

alt.LayerChart(...)

In [ ]:
ca.col_masses_

age                         0.000230
anaemia                     0.000002
creatinine_phosphokinase    0.002201
diabetes                    0.000002
ejection_fraction           0.000144
high_blood_pressure         0.000001
platelets                   0.996400
serum_creatinine            0.000005
serum_sodium                0.000517
sex                         0.000002
smoking                     0.000001
time                        0.000493
DEATH_EVENT                 0.000001
dtype: float64

In [ ]:
ca.row_masses_

0      0.003364
1      0.003435
2      0.002055
3      0.002661
4      0.004142
         ...   
294    0.001969
295    0.003446
296    0.009422
297    0.001808
298    0.005007
Length: 299, dtype: float64

In [ ]:
ca.svd_

SVD(U=array([[-0.00077808, -0.05646208,  0.05736588, ...,  0.05805154,
        -0.01830674, -0.05147869],
       [ 0.41041293, -0.13866369,  0.00061913, ...,  0.04901575,
         0.01392757, -0.04331412],
       [-0.01555482, -0.0210526 ,  0.10726094, ...,  0.05627047,
         0.03823564,  0.0343262 ],
       ...,
       [ 0.01325595, -0.07051277, -0.14239807, ...,  0.01914698,
         0.04017151, -0.01462471],
       [ 0.16537921,  0.11286694, -0.07758678, ..., -0.00481363,
         0.04453548,  0.03057636],
       [-0.03166182,  0.02017697, -0.09815661, ...,  0.0139289 ,
         0.04170015, -0.01669328]]), s=array([0.08130104, 0.02006279, 0.00979161, 0.00375861, 0.00240185,
       0.00197569, 0.001888  , 0.00162754, 0.00156923, 0.00142125,
       0.00126779, 0.00098996]), V=array([[ 1.75925414e-02, -9.57054627e-04,  9.97465160e-01,
         9.42916508e-04,  1.38096906e-02, -1.06880782e-03,
        -4.88013187e-02,  2.51781448e-03,  2.98409142e-02,
         3.65090258e-03,  1.3257

In [ ]:
ca.total_inertia_

0.007145332226891329